/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as HoursRouteImport } from './routes/hours'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ApiNotifyLeadRouteImport } from './routes/api/notify-lead'
import { Route as ApiCloudPublicConfigRouteImport } from './routes/api/cloud-public-config'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminThemeRouteImport } from './routes/admin.theme'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminSpecialsRouteImport } from './routes/admin.specials'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminSectionsRouteImport } from './routes/admin.sections'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminLocationsRouteImport } from './routes/admin.locations'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminImagesRouteImport } from './routes/admin.images'
import { Route as AdminHeroRouteImport } from './routes/admin.hero'
import { Route as AdminContactRouteImport } from './routes/admin.contact'
import { Route as AdminBrandSlideshowRouteImport } from './routes/admin.brand-slideshow'
import { Route as AdminAboutRouteImport } from './routes/admin.about'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const HoursRoute = HoursRouteImport.update({
  id: '/hours',
  path: '/hours',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiNotifyLeadRoute = ApiNotifyLeadRouteImport.update({
  id: '/api/notify-lead',
  path: '/api/notify-lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCloudPublicConfigRoute = ApiCloudPublicConfigRouteImport.update({
  id: '/api/cloud-public-config',
  path: '/api/cloud-public-config',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminThemeRoute = AdminThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSpecialsRoute = AdminSpecialsRouteImport.update({
  id: '/specials',
  path: '/specials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSectionsRoute = AdminSectionsRouteImport.update({
  id: '/sections',
  path: '/sections',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLocationsRoute = AdminLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImagesRoute = AdminImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHeroRoute = AdminHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactRoute = AdminContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrandSlideshowRoute = AdminBrandSlideshowRouteImport.update({
  id: '/brand-slideshow',
  path: '/brand-slideshow',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAboutRoute = AdminAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/hours': typeof HoursRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/brand-slideshow': typeof AdminBrandSlideshowRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/images': typeof AdminImagesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/specials': typeof AdminSpecialsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/theme': typeof AdminThemeRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/cloud-public-config': typeof ApiCloudPublicConfigRoute
  '/api/notify-lead': typeof ApiNotifyLeadRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/hours': typeof HoursRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/brand-slideshow': typeof AdminBrandSlideshowRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/images': typeof AdminImagesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/specials': typeof AdminSpecialsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/theme': typeof AdminThemeRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/cloud-public-config': typeof ApiCloudPublicConfigRoute
  '/api/notify-lead': typeof ApiNotifyLeadRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/hours': typeof HoursRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/brand-slideshow': typeof AdminBrandSlideshowRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/images': typeof AdminImagesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/specials': typeof AdminSpecialsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/theme': typeof AdminThemeRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/cloud-public-config': typeof ApiCloudPublicConfigRoute
  '/api/notify-lead': typeof ApiNotifyLeadRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/hours'
    | '/locations'
    | '/login'
    | '/sitemap.xml'
    | '/admin/about'
    | '/admin/brand-slideshow'
    | '/admin/contact'
    | '/admin/hero'
    | '/admin/images'
    | '/admin/leads'
    | '/admin/locations'
    | '/admin/media'
    | '/admin/sections'
    | '/admin/seo'
    | '/admin/services'
    | '/admin/specials'
    | '/admin/testimonials'
    | '/admin/theme'
    | '/admin/users'
    | '/api/cloud-public-config'
    | '/api/notify-lead'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/hours'
    | '/locations'
    | '/login'
    | '/sitemap.xml'
    | '/admin/about'
    | '/admin/brand-slideshow'
    | '/admin/contact'
    | '/admin/hero'
    | '/admin/images'
    | '/admin/leads'
    | '/admin/locations'
    | '/admin/media'
    | '/admin/sections'
    | '/admin/seo'
    | '/admin/services'
    | '/admin/specials'
    | '/admin/testimonials'
    | '/admin/theme'
    | '/admin/users'
    | '/api/cloud-public-config'
    | '/api/notify-lead'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/hours'
    | '/locations'
    | '/login'
    | '/sitemap.xml'
    | '/admin/about'
    | '/admin/brand-slideshow'
    | '/admin/contact'
    | '/admin/hero'
    | '/admin/images'
    | '/admin/leads'
    | '/admin/locations'
    | '/admin/media'
    | '/admin/sections'
    | '/admin/seo'
    | '/admin/services'
    | '/admin/specials'
    | '/admin/testimonials'
    | '/admin/theme'
    | '/admin/users'
    | '/api/cloud-public-config'
    | '/api/notify-lead'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  HoursRoute: typeof HoursRoute
  LocationsRoute: typeof LocationsRoute
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiCloudPublicConfigRoute: typeof ApiCloudPublicConfigRoute
  ApiNotifyLeadRoute: typeof ApiNotifyLeadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hours': {
      id: '/hours'
      path: '/hours'
      fullPath: '/hours'
      preLoaderRoute: typeof HoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/notify-lead': {
      id: '/api/notify-lead'
      path: '/api/notify-lead'
      fullPath: '/api/notify-lead'
      preLoaderRoute: typeof ApiNotifyLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cloud-public-config': {
      id: '/api/cloud-public-config'
      path: '/api/cloud-public-config'
      fullPath: '/api/cloud-public-config'
      preLoaderRoute: typeof ApiCloudPublicConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/theme': {
      id: '/admin/theme'
      path: '/theme'
      fullPath: '/admin/theme'
      preLoaderRoute: typeof AdminThemeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/specials': {
      id: '/admin/specials'
      path: '/specials'
      fullPath: '/admin/specials'
      preLoaderRoute: typeof AdminSpecialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sections': {
      id: '/admin/sections'
      path: '/sections'
      fullPath: '/admin/sections'
      preLoaderRoute: typeof AdminSectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/locations': {
      id: '/admin/locations'
      path: '/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminLocationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/images': {
      id: '/admin/images'
      path: '/images'
      fullPath: '/admin/images'
      preLoaderRoute: typeof AdminImagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hero': {
      id: '/admin/hero'
      path: '/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AdminHeroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact': {
      id: '/admin/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AdminContactRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/brand-slideshow': {
      id: '/admin/brand-slideshow'
      path: '/brand-slideshow'
      fullPath: '/admin/brand-slideshow'
      preLoaderRoute: typeof AdminBrandSlideshowRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/about': {
      id: '/admin/about'
      path: '/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AdminAboutRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAboutRoute: typeof AdminAboutRoute
  AdminBrandSlideshowRoute: typeof AdminBrandSlideshowRoute
  AdminContactRoute: typeof AdminContactRoute
  AdminHeroRoute: typeof AdminHeroRoute
  AdminImagesRoute: typeof AdminImagesRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminLocationsRoute: typeof AdminLocationsRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminSectionsRoute: typeof AdminSectionsRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSpecialsRoute: typeof AdminSpecialsRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminThemeRoute: typeof AdminThemeRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAboutRoute: AdminAboutRoute,
  AdminBrandSlideshowRoute: AdminBrandSlideshowRoute,
  AdminContactRoute: AdminContactRoute,
  AdminHeroRoute: AdminHeroRoute,
  AdminImagesRoute: AdminImagesRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminLocationsRoute: AdminLocationsRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminSectionsRoute: AdminSectionsRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSpecialsRoute: AdminSpecialsRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminThemeRoute: AdminThemeRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  HoursRoute: HoursRoute,
  LocationsRoute: LocationsRoute,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiCloudPublicConfigRoute: ApiCloudPublicConfigRoute,
  ApiNotifyLeadRoute: ApiNotifyLeadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
