// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient(): SupabaseClient | null {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["VITE_SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["VITE_SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    console.warn(
      `[Supabase] Missing ${missing.join(", ")} — using built-in site defaults until Lovable Cloud / env vars are connected.`,
    );
    return null;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

type SupabaseClient = ReturnType<typeof createSupabaseClient>;

let _supabase: SupabaseClient | null | undefined;

function createUnavailableClient(): SupabaseClient {
  const unavailable = () => {
    throw new Error("Supabase is not configured");
  };
  return new Proxy({} as SupabaseClient, {
    get() {
      return unavailable;
    },
  });
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as SupabaseClient, {
  get(_, prop, receiver) {
    if (_supabase === undefined) {
      _supabase = createSupabaseClient();
    }
    const client = _supabase ?? createUnavailableClient();
    return Reflect.get(client, prop, receiver);
  },
});

