// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient as RealSupabaseClient } from "@supabase/supabase-js";
import {
  isSupabasePublicEnvConfigured,
  readSupabasePublicEnv,
  LOVABLE_CLOUD_BACKEND_HINT,
} from "@/lib/env";
import type { Database } from "./types";

export type SupabaseClient = RealSupabaseClient<Database>;

export function isSupabaseConfigured(): boolean {
  return isSupabasePublicEnvConfigured();
}

function createSupabaseClient(): SupabaseClient | null {
  const { url, key } = readSupabasePublicEnv();

  if (!url || !key) {
    console.warn(`[Lovable Cloud] Backend credentials not in preview — ${LOVABLE_CLOUD_BACKEND_HINT}`);
    return null;
  }

  return createClient<Database>(url, key, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

/** Safe no-op client so the public site still renders without Supabase env vars. */
function createStubClient(): SupabaseClient {
  const emptyResult = { data: null, error: null };
  const emptyList = { data: [] as unknown[], error: null };

  const makeQuery = <T,>(result: { data: T; error: null } = emptyList as { data: T; error: null }) => {
    const promise = Promise.resolve(result);
    const builder = Object.assign(promise, {
      select: () => makeQuery(result),
      eq: () => makeQuery(result),
      neq: () => makeQuery(result),
      order: () => makeQuery(result),
      limit: () => makeQuery(result),
      update: () => makeQuery(result),
      delete: () => makeQuery(result),
      filter: () => makeQuery(result),
      maybeSingle: () => Promise.resolve(emptyResult),
      single: () => Promise.resolve(emptyResult),
      insert: () => Promise.resolve(emptyResult),
      upsert: () => Promise.resolve(emptyResult),
    });
    return builder;
  };

  const auth = {
    onAuthStateChange: () => ({
      data: { subscription: { unsubscribe: () => undefined } },
    }),
    getSession: () => Promise.resolve({ data: { session: null }, error: null }),
    getClaims: () => Promise.resolve({ data: null, error: null }),
    signOut: () => Promise.resolve({ error: null }),
    signInWithPassword: () =>
      Promise.resolve({
        data: { user: null, session: null },
        error: { message: "Lovable Cloud backend is not available in this preview" },
      }),
    signUp: () =>
      Promise.resolve({
        data: { user: null, session: null },
        error: { message: "Lovable Cloud backend is not available in this preview" },
      }),
  };

  const storageFrom = () => ({
    getPublicUrl: (path: string) => ({ data: { publicUrl: path } }),
    list: () => Promise.resolve(emptyList),
    upload: () =>
      Promise.resolve({ data: null, error: { message: "Lovable Cloud backend is not available in this preview" } }),
    remove: () => Promise.resolve(emptyResult),
  });

  const channel = () => {
    const ch: Record<string, unknown> = {};
    ch.on = () => ch;
    ch.subscribe = () => ch;
    return ch;
  };

  return new Proxy({} as SupabaseClient, {
    get(_target, prop) {
      if (prop === "auth") return auth;
      if (prop === "from") return () => makeQuery();
      if (prop === "storage") return { from: storageFrom };
      if (prop === "channel") return channel;
      if (prop === "removeChannel") return () => undefined;
      return () => emptyResult;
    },
  });
}

let _supabase: SupabaseClient | null | undefined;

function getClient(): SupabaseClient {
  if (_supabase === undefined) {
    _supabase = createSupabaseClient();
  }
  return _supabase ?? createStubClient();
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as SupabaseClient, {
  get(_, prop, receiver) {
    return Reflect.get(getClient(), prop, receiver);
  },
});
